package high.concurrent.shop.dao;

import high.concurrent.shop.entity.ProductStock;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProductStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Sun Mar 21 20:34:45 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Sun Mar 21 20:34:45 CST 2021
     */
    int insert(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Sun Mar 21 20:34:45 CST 2021
     */
    int insertSelective(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Sun Mar 21 20:34:45 CST 2021
     */
    ProductStock selectByPrimaryKey(Integer id);

    ProductStock selectByProductId(Integer productId);

    int decreaseStock(@Param("productId") Integer productId, @Param("amount") Integer amount);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Sun Mar 21 20:34:45 CST 2021
     */
    int updateByPrimaryKeySelective(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbg.generated Sun Mar 21 20:34:45 CST 2021
     */
    int updateByPrimaryKey(ProductStock record);
}