package high.concurrent.shop.dao;

import high.concurrent.shop.entity.Promo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PromoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 21 20:34:45 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 21 20:34:45 CST 2021
     */
    int insert(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 21 20:34:45 CST 2021
     */
    int insertSelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 21 20:34:45 CST 2021
     */
    Promo selectByPrimaryKey(Integer id);

    Promo selectByProductId(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 21 20:34:45 CST 2021
     */
    int updateByPrimaryKeySelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Mon Mar 21 20:34:45 CST 2021
     */
    int updateByPrimaryKey(Promo record);
}